### ISSUE TITLE
README, State, and scope

### ISSUE THREAD

**Issue by rossabaker** [djspiewak/shims#1]
The lead paragraph of the readme mentions State, whereas the features section explicitly declares State out of scope.  A framework could utilize `scalaz.State` as a data type and `shims.Monad` as a type class, but this presents different and significant irritations for both Scalaz and Cats users downstream.  I'm guessing one part or the other of the readme is wrong, and that it's the first, but I defer to the author.

**Comment by djspiewak** [comment]
As I am the author of the readme, it seems highly unwise to defer to me.  :-)  I wrote the lead paragraph before I wrote or even really thought through the rest (in fact, I was originally just going to throw some text in there and call it a day; I only fleshed it out into a readme when my fingers didn't stop typing).  I would consider its example to be in err.

Regarding using `State` as a datatype…  Do you mean in an external API?  Can that external API be shimmed in your local peers (e.g. `emm.cats` actually contains other implicits that are specific to `Emm` and cats).  If it's an internal API, then the question becomes whether or not it would be better to simply remove your use of it (or roll your own quickly, since `State` is pretty trivial) to avoid the framework dependency, or actually have the framework dependency.

This is more of a philosophical discussion, but I think there is very definitely a point at which it's worth just putting a stake in the ground and saying "we're dependent on XX".  I think this is partially where the Java logging framework wars went wrong, because all of them are trying to do everything, even the ones that were originally conceived as ways to solve the proliferation problem through wrapping in a common interface (i.e. shims).  I don't want shims to fall into this trap, and so I'm very comfortable saying that, at some point, you just have to use scalaz, or you just have to use cats, and shims won't meet your needs.

*Where* that point falls is really the interesting question.  The readme says `State` is out of scope, so maybe `State` is over the line.  Is `Xor`?  What about slightly more esoteric typeclasses like `MonadIO`.  Does that mean that `IO` is in/out of scope?  It seems like anything that exists in one framework but not the other would be out of scope, but what does that mean for important things like `Hoist` (doesn't exist in cats)?

I think this is a discussion that we need to have.  I mean, I reserve the right to be pointlessly opinionated.  :-)  But shims isn't just for me, and I *want* it to be something that solves the same problem for http4s, and for fs2, and for any other "middleware" library which has this issue.

**Comment by rossabaker** [comment]
Yes, I am talking about types in the public API.  For a concrete example in a library we both know, http4s-core can't break its dependency on Scalaz without a solution for `\/`, `Kleisli`, `EitherT`, and `NonEmptyList`.

The attempt to admit typeclasses and exclude data types is reminiscent of [cats-core's abandoned attempt](https://github.com/non/cats/issues/24).  [This comment in particular](https://github.com/non/cats/issues/24#issuecomment-73379592) presents a variety of interesting techniques.  

* It was reasonable for cats-core to provide `Xor`, but Shims should not.  See aforementioned logger wars.
* Middlewares could roll their own right-biased disjunctions and what not at the cost of glue code.  This seems even worse than `shims.Xor[A, B]`.  
* Using standard types (e.g. `Either`, `A => F[B]`) is the fs2 solution, and appears to be compatible with the current scope of shims.  This results in simple signatures but less satisfactory types than either Cats or Scalaz offer.  This solution costs the end user more than just a shims import.
* I think `OrLike` might provide the most satisfactory experience after it compiles, but the most vexation until it does.  Scalaz and Cats veterans are well used to implicit puzzlers, but it raises the barrier to entry for these middleware libraries.

None of these solutions enthuse me, but the end goal of interoperable libraries that survive the Cats-Scalaz schism does, and I'm glad to be having this discussion.

**Comment by djspiewak** [comment]
Hmm…  I wonder if perhaps shims should use a trick similar to what Rapture does, where the implicits brought into scope by `import shims.cats._` or `import shims.scalaz._` result in widely varying return types from public APIs.  From a framework author's standpoint, this would show up as something like `XorLike` (likely with a slightly kitchier name) that would give you the ability to work in terms of a type which loosely "wraps" scalaz's `\/` and cats' `Xor`, but at the end of the day actually delegates to one of the two depending on implicits.

The advantage here would be two fold.  First, shims would avoid reimplementing All the Things™.  Second, users wouldn't have to work in terms of a wrapper type for `\/` or whatever it is they expect the API to return.  They would get the *real* `scalaz.\/` or `cats.Xor`, depending on their imports.  The disadvantage is pretty pronounced though: the implicits which govern the type selection would need to be in the public signatures of things and threaded through the library, into locations which might be extremely tricky.  I'm thinking here of the fact that http4s is an asynchronous server framework, and thus can have nonlocalized control flow at times, making it hard to thread implicits.

Regarding `EitherT`, if shims does its job correctly and I fix the compile errors in my local branch of `Emm`, you should be able to just use `Emm` to fill that role, since `Emm` itself will sit on top of shims.

**Comment by djspiewak** [comment]
@rossabaker Could you take a look at [feature/either](https://github.com/djspiewak/shims/tree/feature/either)?  Somewhat preliminary, but you can get an idea for what I'm thinking.  Basically, you would perform the following conversion of your APIs:

```scala
// original
def foo(b: Bar): Error \/ Trusted[Bar]

// revised
def foo[\/[_, _]: EitherLike](b: Bar): Error \/ Trusted[Bar]
```

Or something in that direction…  Anyway, the `import shims.scalaz._` or `import shims.cats._` would bring in a single, *unambiguous* instance of `EitherLike` for the corresponding type in the framework in question.  Thus, users would see `scalaz.\/` or `cats.data.Xor`, depending on which they imported.  This seems to be what you were hinting at with the `OrLike` option, earlier.

There are some problems though…  *Storing* these instances and then retrieving them is a problem, since there is nothing in Scala's type system (or Haskell's, for that matter) which enforces coherence of the `EitherLike` instance.  It should be possible to create a wrapper type which allows storage paired with the `EitherLike` instance, but now we're getting into *really* hacky territory.  It also doesn't resolve the second problem that arises from lack of enforced coherence, which is that there is nothing preventing users from passing different `EitherLike` instances to different functions.  You don't have a way of sanely determining that one `EitherLike` is the same as another when those code paths intersect, so… uh… problems.

Rapture gets around this with the cake pattern, which is sort of like a nuclear solution.  Let's call that "plan B".

In an ideal world, framework authors would capture a single `EitherLike` instance once, fixing the type constructor in question, and use that fixed type constructor and typeclass in all endpoints seamlessly.  I'm just not quite sure how to accomplish that, though.

**Comment by rossabaker** [comment]
The "Rapture modes" trick is also employed by [Parboiled2 Delivery Schemes](https://github.com/sirthias/parboiled2#alternative-deliveryschemes), which http4s [defines for `\/`](https://github.com/http4s/http4s/blob/v0.11.3/core/src/main/scala/org/http4s/parser/ScalazDeliverySchemes.scala).  At least that's a well-contained thing that most of our users are unaware of.

My head still spins thinking about http4s-on-fs2:
* This trick could certainly banish `scala.Either` from the http4s API, but it would continue to return `fs2.Task`, which is on Team `Either`.  It's still unpleasantly mix-and-match.  (This is true even if http4s picks sides in Cats vs. Scalaz instead of shimming.)
* We might abstract to `type HttpService[F] = Kleisli[F, Request[F], Response[F]]`, and let users pick a more native Task-like thing, if such things were to materialize.  Parameterizing `Request` and `Response` for the effects of their body streams is unpleasant, which is why it's not already done.  Perhaps I would benefit from studying Rapture's use of cake here.
* http4s could surrender and just use `scala.Either` for consistency with its own dependency.  If several FP libraries make this decision, then user code becomes littered with `.fromEither` or comprehensions full of `.right`, and everybody loses.

**Comment by aloiscochard** [comment]
@rossabaker @djspiewak is there also a performance penalty by using such hack vs a unique typeclass?

**Comment by djspiewak** [comment]
@rossabaker I think that, if we can get shims into a state where it supports everything that http4s needs, it will also support everything that fs2 needs.  I have very little doubt that they would use it rather than rolling their own duplicates of everything.  Paul's stated goal is to avoid "picking a winner", and shims *should* be the best way to achieve that (it isn't yet, but it should be).  At the very least, you shouldn't have to worry about `scala.Either`.

I'm still thinking pretty hard about ways to manage the delegate capturing.  The cake pattern does make it pretty straightforward, even if you're just using the cake as a straightforward module wrapper, but it does have a fairly significant impact on every piece of code in the framework, and it's not completely invisible to users (at least, users who read scaladoc).  Also, there are still a lot of bugs in scalac related to types nested within traits, so it's hardly something that comes without cost.

@aloiscochard I believe that the overhead would be largely limited to a few megamorphic delegate functions and the allocation cost of an `HList`.  Not non-existent, but likely still small.

**Comment by djspiewak** [comment]
@rossabaker I've solved the `Either` problem… more or less.

It comes down to the fact that shims is only relevant for the *surface* API.  It really doesn't matter what you're using in the implementation!  In other words, it's completely safe to have an API which uses `EitherLike`.  Internally, you can be using `scala.util.Either`, or `scalaz.\/`, or something else completely altogether, as long as the typeclass provides you with enough machinery to convert from your abstraction into whatever type the user is expecting.  For efficiency, I would imagine it would be worth specializing some of this machinery a bit, so that we can avoid a series of allocations in the event that you and your users happen to be using the same backing implementation.

So anyway, this may or may not be a better solution than just right-projecting `scala.util.Either`.  WDYT?

**Comment by tpolecat** [comment]
I have been playing around with doing this for atto with `NonEmptyListy`, `Eithery`, `Semigroupy`, `Foldy`, etc. typeclasses and it works ok, but it has the distinct flavor of something that's approachable in specific cases but will be hard (or at least very irritating) in the general case. Beyond the choice of what's in and what's out, there are differences in variance and strictness between cats and scalaz that I am able to sweep under the rug because I know they don't matter for me, but in the general case I think it could be hard.

Which is in no way intended to discourage your effort here, just a data point. So many people are thinking about this problem now that I'm pretty confident we will be able to come up with *at least* some viable scaffolding.

Mostly I just wanted to get on the canoe for this issue because it interests me. :chicken:

**Comment by djspiewak** [comment]
By all means, @tpolecat, get in the canoe.  :-)  Regarding variance differences and such…  Shims is always going to be a least common denominator of sorts.  It's going to have to sweep many of those things under the rug, and if it doesn't work, then people will just be constrained.  We're not going to be able to provide a "best of both worlds" solution in any sense of the phrase.  Life sucks, and we're a logging framework for typeclasses.

I think the thing to think about with respect to `NonEmptyListy` and friends is what the end-user experience is like, since *that* is what we're trying to optimize for.  In an ideal world, users will just use cats or scalaz with http4s/fs2/tut/whatever and never even realize that the middleware framework *wasn't* designed specifically with their framework of choice in mind.  Whether this is realistic is another question, but ideally we can approach that goal as closely as possible.

What I'm saying is that I don't mind if middleware authors get inconvenienced, perhaps to a significant degree.  It's not ideal, obviously, but if we need to make an optimization tradeoff, middleware gets the short end of the stick.
