### ISSUE TITLE
LiftIO for Sync is incorrect

### ISSUE THREAD

**Issue by fommil** [djspiewak/shims#22]
but don't feel so bad. I fell for it too, and it took me a couple of attempts.

The trouble is that using `LiftIO` will lift the wrong thing when you have an `EitherT` in there, plus you can get into all kinds of horrible infinite loops because `Sync` extends `MonadError` and typeclass incoherence ensues...

The correct solution is to provide a custom instance for each thing, and not rely on the MonadIO. My variant (but for ioeffect) is here https://gitlab.com/fommil/upgrade-typelevel-to-scalaz/blob/master/src/main/scala/ScalazCats.scala#L172-272

(this is not cats-effect's `Sync`, but one adapted to scalaz to allow upgrading cats to scalaz).

Finally, incase you weren't aware, scalaz-ioeffect already provides an `Effect` instance.

**Comment by djspiewak** [comment]
@fommil I think I'm missing something… What are you saying exactly? Can you provide an example? Also I'm pretty sure I'm not relying on `MonadIO` at all.

> Finally, incase you weren't aware, scalaz-ioeffect already provides an Effect instance.

My understanding is that scalaz-ioeffect is a) scalaz 7.3-specific, and b) providing an `Effect` instance for the backport of John's new `IO`. If it's actually relative to 7.2, then it would probably be ideal if scalaz-ioeffect brought in `shims-effect` and mixed in the `ShimsEffect` trait, otherwise people using shims and scalaz-ioeffect in the same namespace will run into ambiguity issues due to the fact that `Effect` implies `Monad` (i.e. the same problem which led to the creation of shims-effect in the first place.

**Comment by fommil** [comment]
sorry I mean `LiftIO`, not `MonadIO`. There will be no `LiftIO` in scalaz 7.3 since it is lawless. In any case, I was mistaken. I skimmed your code as providing a `Sync` for anything with a `LiftIO` but you are only providing `Sync[IO]` and not doing anything for the monad transformers. If you decide to provide instances for the scalaz monad transformers, you will need my code above. (I tried to do this generically for anything with a `MonadError[F, Throwable]` and a `LiftIO` but hit the problems described).

https://github.com/scalaz/ioeffect is built for scalaz 7.2 :smile: and comes with a convenient `Applicative.Par` instance, along with `.parTraverse` and `.parApply` working out of the box since 7.2.25.

We're leaving the `scalaz.effect` and `scalaz.concurrent` package alone to avoid breaking bincompat. No need for shims to do anything as `import scalaz.ioeffect.catz._` should "just work".

**Comment by djspiewak** [comment]
> There will be no LiftIO in scalaz 7.3 since it is lawless.

It's parametric; there really isn't any need for laws. There's exactly one thing it can do. But that's a discussion for a different issue tracker.

> If you decide to provide instances for the scalaz monad transformers, you will need my code above.

This is part of why I decided not to do that. :-) Also scalaz 7.2/7.3's MTL is kind of a mess and not useful in a lot of contexts. The encoding is too fragile. Practically, you either need something like cats-mtl (or the quasar-contrib reencoding) or scalaz 8. So there isn't much need to shim them out, since no one can make practical use of them anyway.

> No need for shims to do anything as import scalaz.ioeffect.catz._ should "just work".

Put the following at the top of a file:

```scala
import shims._
import scalaz.ioeffect.catz._
```

Then call `traverse` on something of type `IList[IO[A]]`. This illustrates the problem pretty nicely. Like I said, I don't think it's going to be a very common use-case for people to want to use the new `IO` *and* shims in the same scope, but in the event that they do, they're going to run into these sorts of issues. The only workaround is to depend in shims and mix in `ShimsCore` (or shims-effect and mix in `ShimsEffect`), as described in [extending.md](https://github.com/djspiewak/shims/blob/master/extending.md).

**Comment by fommil** [comment]
Everything is broken.

![](https://media.giphy.com/media/bDTtPo3HyEluE/giphy.gif)
