### ISSUE TITLE
Parallel Instance for Task seems plausible

### ISSUE THREAD

**Issue by ChristopherDavenport** [djspiewak/shims#27]
I understand what is stated in the README and I totally agree. I've had this contribution to scalaz-task-effect.

https://github.com/ChristopherDavenport/scalaz-task-effect/pull/46

I've been trying to push people over to this repository, however that is a slow process. So I wanted to bring this over and make it known, and possibly use over here.

I've asked to validate the Applicative instance, but if the Applicative of Parrallel task checks, it seems it would have a place.

**Comment by djspiewak** [comment]
`Parallel` for `Task` definitely seems possible. I haven't looked into it too much. I would certainly accept such a PR. I haven't really had much time to do much with my OSS stuff beyond what I've needed for work though, so it might have to wait a while for me to get to it. :-)

**Comment by joroKr21** [comment]
I can work on adding it here as well once I'm done with ChristopherDavenport/scalaz-task-effect#46 I know about shims and thank you for the great work, it's no small achievement, I just prefer the more lightweight option, no macros involved.

**Comment by djspiewak** [comment]
@joroKr21 The problem with the more lightweight option is you'll get instance conflicts because `Effect` is a subtype of `Monad`. Practically speaking, any time you're using `Task` within the context of a cats-dependent framework, you're *also* going to want shims to handle all the other conversions for you. But you can't really mix shims with some other conversions framework. This is why shims-effect exists.

It's also worth noting that the macros only exist as a workaround for a bug in scalac. None of the conversions *themselves* are macros, only the implicit resolution. Everything compiles without macros on dotty.

**Comment by joroKr21** [comment]
Ok I bit the bullet and migrated to shims. It was easier than expected. There were some ambiguous implicits as I feared but not that many and they could be avoided by carefully managing what to import from `shims.effect`.

**Comment by djspiewak** [comment]
@joroKr21 I'd be curious as to what implicits you found to be ambiguous? That usually comes down to one of two things:

- Shims itself is incorrectly organized (has happened a few times)
- You have your own converters which conflict

The latter can be resolved by using the `ShimsCore` (or `ShimsEffect`) mixin on the `object` which contains your converters, and then only importing from that object, rather than importing from there and from shims.

I would guess you're seeing the former though, and usually it's resolvable on shims' end.

**Comment by joroKr21** [comment]
I guess the most common case is when I have two unrelated paths through implicits which can give me a `Monad`. For example having both `Sync` and `MonadReader` (from Scalaz) which were not ambiguous before.

**Comment by djspiewak** [comment]
Yeah unfortunately that's a systematic problem with the way that Scalaz encodes MTL witnesses. You would have the same issue if you had a `scalaz.MonadError` and a `scalaz.MonadReader` in scope at the same time.

We get around this in quasar by using the same trick that cats-mtl uses, which is to say, we have our own `MonadReader` which is exactly the same *except* it doesn't extend `Monad`.

**Comment by joroKr21** [comment]
We made our own artificial hierarchy but it doesn't include cats instances (because they don't have this problem). I guess the next step would be a full-blown prelude as you suggested.
