### ISSUE TITLE
Should Effect[Task].async catch exceptions thrown by the callback registry?

### ISSUE THREAD

**Issue by joroKr21** [djspiewak/shims#29]
It looks like `scalaz.concurrent.Task` is catching less exceptions than `cats.effect.IO`. Compare:
https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/IO.scala#L1058
with:
https://github.com/scalaz/scalaz/blob/series/7.3.x/concurrent/src/main/scala/scalaz/concurrent/Future.scala#L395

This is not really specified in a law but could be unexpected for users. I noticed that while using the default `Async.shift[Task]` which can throw a `RejectedExecutionException` by the underlying `ExecutionContext`.

**Comment by djspiewak** [comment]
We can definitely catch the exception. I was the one who added the semantic as it stands today in `IO`, and I obviously like it, but it's intentionally unspecified in the laws because of how it interacts with execution models. Overall, I think it's probably better to catch it whenever possible, and it's obviously possible here.
